# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-22 20:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accountability', '0003_auto_20180422_1656'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True, null=True)),
                ('specialty', models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accountability.Specialties')),
            ],
        ),
        migrations.AlterField(
            model_name='session',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountability.Subjects'),
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
