# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-22 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountability', '0004_auto_20180422_2354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjects',
            name='specialty',
        ),
        migrations.AddField(
            model_name='subjects',
            name='specialty',
            field=models.ManyToManyField(to='accountability.Specialties'),
        ),
    ]
