# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-23 19:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountability', '0005_auto_20180423_0000'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Session',
            new_name='Appraisals',
        ),
        migrations.RenameField(
            model_name='appraisals',
            old_name='data',
            new_name='changed_date',
        ),
    ]
