# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-23 21:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accountability', '0006_auto_20180423_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appraisals',
            name='changed_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
